name = "stage-test"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "stage-test_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "stage-test.wasm"
command = "npm run build:release"
